import { siteUrl } from "../(seo)/seo-pages";

export type BlogContentBlock =
  | { type: "paragraphs"; paragraphs: readonly string[] }
  | { type: "list"; items: readonly string[] }
  | { type: "table"; headers: readonly string[]; rows: readonly (readonly string[])[] }
  | { type: "subheading"; heading: string };

export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  category: string;
  author: string;
  published: boolean;
  publishedAt: string;
  modifiedAt: string;
  readingTime: string;
  intro: string;
  sections: readonly { id: string; heading: string; content: readonly BlogContentBlock[] }[];
  relatedSlugs: readonly string[];
  internalLinks: readonly { label: string; href: string }[];
  cta: string;
};

const p = (...paragraphs: string[]): BlogContentBlock => ({ type: "paragraphs", paragraphs });
const list = (...items: string[]): BlogContentBlock => ({ type: "list", items });
const table = (headers: string[], rows: string[][]): BlogContentBlock => ({ type: "table", headers, rows });
const article = (post: Omit<BlogPost, "author" | "published" | "publishedAt" | "modifiedAt"> & { published?: boolean }): BlogPost => ({
  ...post, author: "TradeLore", published: post.published ?? true, publishedAt: "2026-07-22", modifiedAt: "2026-07-22",
});

const links = {
  journal: { label: "Trading journal for Indian traders", href: "/trading-journal-india" },
  product: { label: "See the TradeLore product workflow", href: "/product" },
  analytics: { label: "Explore trading performance analytics", href: "/features/trading-analytics" },
  replay: { label: "Review trades with trade replay", href: "/features/trade-replay" },
  notes: { label: "Explore the trading journal feature", href: "/features/trading-journal" },
};

export const blogPosts = [
  article({ slug: "best-trading-journal-india", title: "Best Trading Journals for Indian Traders in 2026", description: "A practical, transparent comparison of spreadsheets, broker reports, and trading-journal software for Indian traders.", category: "Trading journal", readingTime: "9 min read", intro: "The best trading journal for an Indian trader is the one that captures reliable executions, useful context, and reviewable patterns without making record-keeping harder than the trading itself.", sections: [
    { id: "what-to-evaluate", heading: "What Indian traders should evaluate", content: [p("Start with the workflow, not the feature list. Ask whether a tool can represent equities, futures and options, import the data you actually receive, and preserve the reason behind a trade."), list("Indian broker support and the segments you trade", "Automatic import plus a dependable CSV fallback", "Journaling for thesis, mistakes, emotion and lessons", "Analytics for net P&L, setup, time and holding period", "Security, data ownership and a pricing model you understand") ] },
    { id: "comparison", heading: "Trading journal comparison", content: [table(["Dimension", "Excel / Sheets", "Broker report", "TradeLore", "Other platforms"], [["Indian broker support", "Manual or custom", "One broker", "Repository-verified broker workflows", "[SOURCE REQUIRED: current competitor capability]"], ["F&O support", "Possible with design", "Depends on broker", "Trade and segment fields from imported data", "[SOURCE REQUIRED: current competitor capability]"], ["Automatic import", "No", "Native to source", "Available for supported integrations", "[SOURCE REQUIRED: current competitor capability]"], ["CSV import", "Native", "Export-dependent", "Available through import workflow", "[SOURCE REQUIRED: current competitor capability]"], ["Journaling and analytics", "You build it", "Limited context", "Journal, reports and review workflow", "[SOURCE REQUIRED: current competitor capability]"], ["Trade replay", "Manual", "Usually report-led", "Available in product workflow", "[SOURCE REQUIRED: current competitor capability]"], ["Pricing and security", "Spreadsheet account or file", "Broker account", "See current plan and security information", "[SOURCE REQUIRED: current competitor pricing/security]"]]) ] },
    { id: "evaluation", heading: "How we evaluated these tools", content: [p("This is a workflow comparison, not a ranking. The TradeLore column is based on the current repository: static public pages, broker adapters, import routes, trade matching, journaling components and reports. Competitor rows are deliberately marked where current information needs verification."), p("Before choosing, test one week of real or demo data. Check whether fills match correctly, costs can be reviewed, notes are easy to add, and the output helps you make a specific next-session change.")] },
    { id: "fit", heading: "Which type of trader may prefer each option?", content: [table(["User type", "Likely fit"], [["Occasional trader", "A simple spreadsheet may be enough."], ["Systematic reviewer", "A journal with imports, tags and analytics reduces manual work."], ["F&O trader", "Use a tool that preserves contract and execution context."], ["Trader testing a process", "Start small and prioritise review quality over dashboards."]]), p("TradeLore is one option for traders who want broker data, journal context and performance review in one workflow. It is not objectively the best choice for every trader.")] },
  ], relatedSlugs: ["trading-journal-template-india", "broker-pnl-report-vs-trading-journal"], internalLinks: [links.journal, links.product, { label: "View pricing", href: "/pricing" }], cta: "Compare your current workflow with TradeLore using a small set of real trades." }),

  article({ slug: "trading-journal-template-india", title: "Free Trading Journal Template for Indian Traders", description: "Build a practical Excel or Google Sheets trading journal template for Indian equities, futures and options.", category: "Templates", readingTime: "8 min read", intro: "A useful trading journal template records the planned decision, the executed trade, the cost of the trade, and the lesson you can apply next time.", sections: [
    { id: "columns", heading: "Columns to include", content: [table(["Group", "Columns"], [["Trade identity", "Trade date, instrument, market, strategy, direction"], ["Execution", "Entry, exit, quantity, stop-loss, target"], ["Outcome", "Gross P&L, charges, net P&L"], ["Risk", "Planned risk, realised R-multiple"], ["Review", "Screenshot, mistake, emotion, lesson"]]), p("Keep one row per completed trade if your workflow is simple. For multi-leg options, use a trade ID so several legs can be reviewed together without pretending they were one fill.")] },
    { id: "formulas", heading: "Formulas that are mathematically sound", content: [p("For a long position, gross P&L is (exit price − entry price) × quantity. For a short position, it is (entry price − exit price) × quantity. Net P&L is gross P&L − charges."), p("If planned risk is positive, realised R-multiple is net P&L ÷ planned risk. Enter the risk in rupees, not as a percentage, unless you first convert the percentage into a rupee amount. Do not hard-code brokerage, taxes or statutory rates: they vary by broker, product and regulation."), list("Use data validation for direction and market.", "Store a date and time consistently, preferably in separate columns.", "Use a link to a screenshot rather than embedding large images in every row.", "Add a unique trade ID before importing or merging data.")] },
    { id: "template", heading: "A workable sheet layout", content: [p("Create an Inputs sheet for trades, a Lists sheet for strategy and mistake tags, and a Review sheet for pivot tables or summaries. Protect formula columns so a hurried edit does not change historical results."), p("[DOWNLOAD REQUIRED: attach the final Excel or Google Sheets template]") ] },
    { id: "limits", heading: "When a spreadsheet becomes difficult", content: [p("Spreadsheets become fragile when you reconcile repeated fills, calculate costs, review multi-leg trades, keep screenshots, and maintain formulas across many months. They are still a sensible starting point: the warning sign is not the number of rows alone, but the amount of manual reconciliation and the number of places a value can disagree.")] },
  ], relatedSlugs: ["how-to-maintain-fno-trading-journal", "trading-journal-metrics"], internalLinks: [{ label: "Automated trade import", href: "/features/automated-trade-import" }, links.notes, { label: "View pricing", href: "/pricing" }], cta: "Start with the smallest template that captures decisions you will actually review." }),

  article({ slug: "how-to-maintain-fno-trading-journal", title: "How to Maintain a Trading Journal for F&O Trading", description: "A practical guide to recording futures and options trades before, during and after execution.", category: "F&O journaling", readingTime: "9 min read", intro: "An F&O trading journal should connect the contract details to the decision: what you traded, why you traded it, how risk was defined, and what the exit taught you.", sections: [
    { id: "before", heading: "Before the trade", content: [p("Record the underlying, instrument, strike price, expiry, option type, long or short direction, lot size, stop-loss and target. Add the thesis and the condition that would invalidate it."), list("Underlying and market context", "Contract, expiry, strike and option type", "Entry plan, planned risk, stop-loss and target", "Expected scenario and invalidation", "Whether the trade is part of a defined multi-leg strategy")] },
    { id: "during", heading: "During execution", content: [p("Note the actual premium or futures price, quantity, timestamps, order changes and any partial exits. A short option and a long option can have different risk narratives even when they share an underlying."), p("For a multi-leg strategy, keep a shared strategy ID and record each leg separately. Review the combined result, but retain leg-level prices and quantities so you can explain slippage, hedging and partial exits.")] },
    { id: "after", heading: "After the trade", content: [p("Complete the exit reason, charges, net P&L, mistake tags, emotional state and lesson while the sequence is fresh. Review whether the result came from the thesis, execution, position sizing or a rule violation."), table(["Field", "Fictional example"], [["Underlying", "NIFTY"], ["Contract", "NIFTY 25,000 CE"], ["Expiry / type", "26 Jun 2026 / call"], ["Direction", "Long"], ["Entry / exit", "₹120 / ₹145"], ["Quantity", "75"], ["Review", "Thesis was valid; exit followed target"]]) ] },
    { id: "disclaimer", heading: "Use the journal for review, not recommendations", content: [p("The example is anonymised and educational. It is not a trade recommendation. A journal cannot remove market risk; it can make decisions and recurring behaviour easier to examine.")] },
  ], relatedSlugs: ["how-to-review-options-trade-example", "calculate-net-trading-pnl-india"], internalLinks: [{ label: "F&O trading journal", href: "/futures-options-trading-journal" }, { label: "Options trading journal India", href: "/options-trading-journal-india" }, links.notes], cta: "Record the contract details first; review the behaviour second." }),

  article({ slug: "calculate-net-trading-pnl-india", title: "How to Calculate Net Trading P&L After Brokerage and Charges", description: "Understand gross P&L, brokerage, exchange charges, statutory charges, taxes and net trading P&L in India.", category: "Trading calculations", readingTime: "7 min read", intro: "Net trading P&L is what remains after the costs attached to executing a trade are deducted from gross P&L.", sections: [
    { id: "components", heading: "The components of net P&L", content: [table(["Component", "Meaning"], [["Gross P&L", "Price movement multiplied by quantity and direction"], ["Brokerage", "Broker fee, where applicable"], ["Exchange charges", "Charges levied by the relevant exchange"], ["Statutory charges", "Government or regulatory charges"], ["Taxes", "Applicable taxes such as GST or transaction taxes"], ["Net P&L", "Gross P&L minus applicable costs"]]), p("[SOURCE REQUIRED: current applicable Indian trading charges and official source]") ] },
    { id: "example", heading: "A generic worked example", content: [p("Suppose a fictional long trade buys 100 units at ₹100 and sells at ₹103. Gross P&L is (₹103 − ₹100) × 100 = ₹300. If the broker statement shows ₹12 brokerage, ₹4 exchange charges and ₹9 statutory charges and taxes, total charges are ₹25 and net P&L is ₹275."), p("This is arithmetic, not a current fee schedule. Use the contract note or verified broker statement for actual amounts. Do not copy the example rates into a live calculator.")] },
    { id: "why-costs", heading: "Why trading costs matter", content: [p("Costs reduce every trade's result, so a strategy with small average wins can look different after charges. Compare like with like: use net P&L, the same date range, and the same treatment of partially closed positions."), p("Charges vary by broker, market, product, order type and regulation. Check the applicable contract note and official source before making a financial decision.")] },
  ], relatedSlugs: ["broker-pnl-report-vs-trading-journal", "trading-journal-metrics"], internalLinks: [links.analytics, links.journal], cta: "Use net results in reviews so your journal reflects the cost of execution." }),

  article({ slug: "broker-pnl-report-vs-trading-journal", title: "Broker P&L Report vs Trading Journal: What Traders Are Missing", description: "Understand what broker reports show and what a structured trading journal adds for review and decision-making.", category: "Trading review", readingTime: "7 min read", intro: "A broker P&L report answers what was bought, sold and settled. A trading journal adds the reasoning and behaviour needed to review those decisions.", sections: [
    { id: "difference", heading: "The difference in one table", content: [table(["Question", "Broker P&L report", "Structured journal"], [["What happened?", "Orders, fills and financial result", "Imported result plus context"], ["Why did it happen?", "Usually not recorded", "Thesis, setup and invalidation"], ["What should change?", "Not a report purpose", "Mistake tags and lessons"], ["How did behaviour affect it?", "Limited", "Psychology, rule adherence and sizing"], ["How can I review it?", "Statement or report filters", "Workflows, playbooks, replay and analytics"]]) ] },
    { id: "adds", heading: "What a journal adds", content: [list("Trade reasoning and the original plan", "Mistake tracking with consistent tags", "Strategy or playbook classification", "Psychology and emotional state", "Time-of-day and holding-time analysis", "A repeatable weekly review workflow") ] },
    { id: "use-both", heading: "Use both sources", content: [p("The broker report remains important for official financial records. A journal is a review layer built from imported data and your own observations. Reconcile the two when numbers differ, and avoid treating a note as a replacement for a contract note."), p("TradeLore is designed for this second layer: broker imports and CSV workflows feed journaling, matching, reports and replay. It does not place, modify or cancel orders.")] },
  ], relatedSlugs: ["best-trading-journal-india", "trading-journal-metrics"], internalLinks: [links.analytics, links.notes, links.product], cta: "Keep the broker report for records and use the journal to understand the decisions." }),

  article({ slug: "import-zerodha-trades-trading-journal", title: "How to Import Zerodha Trades Into a Trading Journal", description: "Documented TradeLore workflow for connecting Zerodha trade fills, matching trades and reviewing imported data.", category: "Broker tutorials", readingTime: "6 min read", intro: "TradeLore's repository contains a Zerodha connection flow that fetches trade fills, normalises instrument metadata and matches executions into reviewable trades.", sections: [
    { id: "workflow", heading: "The supported workflow", content: [p("The implementation uses a Zerodha connection flow, an access token session and a server-side fetch of trade fills. It normalises exchange, symbol, segment, instrument token, fill time, order ID, trade ID, side, quantity and average price before sending orders through the shared trade-order sync pipeline."), p("TradeLore is read-only for this workflow: it imports data for journaling and analytics and does not place, modify or cancel orders."), p("[SOURCE REQUIRED: verify current Zerodha export or connection workflow]") ] },
    { id: "matching", heading: "Historical data, matching and duplicates", content: [p("The code fetches the current broker trade data and uses stable broker, user, order and trade identifiers when normalising fills. The shared pipeline then persists orders and matches them into completed trades. This protects the import path from treating the same fill as a new trade on every sync; verify the current retention and historical range before promising a specific look-back period."), p("[SCREENSHOT PLACEHOLDER: Zerodha connection and import status in TradeLore]") ] },
    { id: "errors", heading: "Common errors to check", content: [list("Connection or token expiry: reconnect through the broker setup flow.", "Missing identifiers or invalid quantity/price: the normaliser rejects incomplete fills.", "Instrument metadata mismatch: confirm the current instrument index can be fetched.", "Unexpected totals: compare imported fills with the broker's source data before reviewing P&L.")] },
  ], relatedSlugs: ["broker-pnl-report-vs-trading-journal", "trading-journal-template-india"], internalLinks: [{ label: "Zerodha broker workflow", href: "/brokers/zerodha" }, { label: "Automated trade import", href: "/features/automated-trade-import" }, { label: "View pricing", href: "/pricing" }], cta: "Connect a read-only workflow, verify one session, then begin your review." }),

  article({ slug: "import-dhan-trades-trading-journal", title: "How to Import Dhan Trades Into TradeLore", description: "A repository-grounded overview of TradeLore's Dhan trade import, normalisation, options fields and matching workflow.", category: "Broker tutorials", readingTime: "6 min read", intro: "TradeLore's Dhan integration fetches trade data, normalises it into common trade-order fields, and sends it through the shared matching pipeline.", sections: [
    { id: "connection", heading: "Connection and import", content: [p("The Dhan client supports profile and trade-book requests through the configured Dhan credentials and consent flow. The sync converts valid records with trade ID, order ID, symbol, side, quantity, price, time, exchange segment and instrument details into TradeLore trade orders."), p("[SOURCE REQUIRED: verify current Dhan export or API workflow]") ] },
    { id: "segments", heading: "Data and options handling", content: [p("The normaliser preserves the exchange segment and derives exchange and instrument type fields where present. The repository test covers an NFO options record with CE type, quantity and price, so options records can be represented when the source supplies those fields. Do not infer a missing strike or expiry from a display name."), p("Historical availability depends on the broker response and the current sync request. Verify the returned date range before describing it as unlimited history.")] },
    { id: "troubleshooting", heading: "Duplicate prevention and troubleshooting", content: [p("Dhan records are assigned stable identifiers using broker, client, order and trade IDs and then pass through the common sync pipeline. If totals look wrong, compare source trades, date filters, segment values and rejected rows before importing again."), list("Reconnect if consent or credentials are invalid.", "Check that quantity, price, side, order ID and trade ID are present.", "Review the sync status and error returned by the broker route.", "Use a small date range or one session to validate the first import.")] },
  ], relatedSlugs: ["import-upstox-trades-trading-journal", "how-to-maintain-fno-trading-journal"], internalLinks: [{ label: "Dhan broker workflow", href: "/brokers/dhan" }, { label: "Automated trade import", href: "/features/automated-trade-import" }], cta: "Validate one Dhan session end to end before relying on a larger history." }),

  article({ slug: "import-upstox-trades-trading-journal", title: "How to Import Upstox Trades Into a Trading Journal", description: "Learn how TradeLore's Upstox integration requests historical trades, normalises fields and prepares them for journal review.", category: "Broker tutorials", readingTime: "6 min read", intro: "TradeLore's Upstox integration requests historical trades by segment and date range, normalises the response, and matches the result into the journal workflow.", sections: [
    { id: "connect", heading: "Connect and request historical trades", content: [p("The implementation uses an Upstox login and callback flow, then requests historical trades through the broker endpoint for configured segments and paginated date ranges. The sync combines those responses before normalising them."), p("[SOURCE REQUIRED: verify current Upstox export or API workflow]") ] },
    { id: "fields", heading: "Imported fields and supported instruments", content: [p("The normaliser retains the source trade ID, date, segment, exchange, symbol, side, quantity and price, and maps option type where supplied. The current code maps equity distinctly and handles futures/options segments according to the source response. It is safer to verify a live account's segment coverage than to assume every instrument is supported."), p("Historical import is request-based and paginated; the precise date window is implementation-dependent and should be checked in the current sync configuration.")] },
    { id: "security", heading: "Errors and security", content: [list("Reconnect when the access token or callback state is invalid.", "Inspect segment and date parameters when a session is missing.", "Compare imported totals with Upstox before reviewing performance.", "Keep credentials in the authenticated connection flow and revoke access through the broker when no longer needed.")] },
  ], relatedSlugs: ["import-dhan-trades-trading-journal", "import-angel-one-trades-trading-journal"], internalLinks: [{ label: "Upstox broker workflow", href: "/brokers/upstox" }, { label: "Automated trade import", href: "/features/automated-trade-import" }], cta: "Treat the first Upstox sync as a reconciliation exercise, not a reporting shortcut." }),

  article({ slug: "import-angel-one-trades-trading-journal", title: "How to Import Angel One Trades Into a Trading Journal", description: "A verified-code overview of TradeLore's Angel One trade-book workflow, imported fields and troubleshooting checks.", category: "Broker tutorials", readingTime: "5 min read", intro: "TradeLore's Angel One adapter reads trade-book records, normalises valid fills and passes them into the common trade matching pipeline.", sections: [
    { id: "flow", heading: "Connection and CSV boundaries", content: [p("The repository contains an authenticated Angel One client and a trade-book request. The normaliser accepts order ID, fill ID, symbol, exchange, side, fill size, fill price and fill time, then derives an equity segment for NSE and BSE records while preserving other exchange values."), p("[SOURCE REQUIRED: verify current Angel One export or API workflow]") ] },
    { id: "capabilities", heading: "What is imported", content: [p("Valid records with identifiers, a symbol, a timestamp, positive quantity and price, and BUY or SELL direction become common TradeLore trade orders. The shared pipeline then persists them and matches executions. The repository does not justify claims about unlimited historical access or every Angel One segment, so confirm those from the current response."), p("TradeLore uses this data for journaling and analytics. It does not place, modify or cancel orders.")] },
    { id: "troubleshooting", heading: "Troubleshooting and security", content: [list("Re-authenticate when credentials or the session are rejected.", "Check that fill ID, order ID, symbol, time, quantity, price and side are present.", "Compare source trade-book totals before repeating an import.", "Use the broker's credential controls to revoke access when needed.")] },
  ], relatedSlugs: ["import-zerodha-trades-trading-journal", "broker-pnl-report-vs-trading-journal"], internalLinks: [{ label: "Angel One broker workflow", href: "/brokers/angel-one" }, { label: "Automated trade import", href: "/features/automated-trade-import" }], cta: "Verify the fields that arrived before adding journal conclusions." }),

  article({ slug: "delta-exchange-india-trading-journal", title: "How to Journal Delta Exchange India Futures Trades", description: "A TradeLore guide to Delta fills, funding, fees and perpetual-futures review, based on the current integration.", category: "Crypto futures", readingTime: "7 min read", intro: "TradeLore's repository contains a Delta Exchange workflow for API and CSV imports, fill matching and funding-aware review. Verify current exchange terminology before relying on operational instructions.", sections: [
    { id: "status", heading: "What the integration supports", content: [p("The repository includes Delta credentials, fill sync, product metadata, wallet or funding enrichment, CSV import, trade matching and a process-local sync lock. TradeLore imports data for journaling and analytics; it does not place trades or withdraw funds."), p("[SOURCE REQUIRED: verify current Delta Exchange India terminology and workflow]") ] },
    { id: "review-model", heading: "What a complete review should distinguish", content: [list("Orders versus fills: a journal should review executed fills, not only submitted orders.", "Long and short positions, including partial exits.", "Fees and funding as separate cost or cash-flow concepts.", "Settlement currency, leverage and perpetual-futures terminology.", "The difference between an API sync and a CSV import.")] },
    { id: "next", heading: "What to verify in your account", content: [p("Confirm the supported contract set, source fields, historical range, fee and funding treatment, settlement currency and duplicate behaviour against the current account workflow. Product, API and exchange terminology can change, so verify current details before following operational instructions.")] },
  ], relatedSlugs: ["trading-journal-metrics", "calculate-net-trading-pnl-india"], internalLinks: [{ label: "Delta Exchange broker page", href: "/brokers/delta-exchange" }, links.analytics], cta: "Use this draft as a verification checklist before publishing Delta-specific guidance." }),

  article({ slug: "trading-journal-metrics", title: "The 15 Most Important Trading Journal Metrics", description: "Definitions, formulas, interpretations and limitations for 15 trading journal metrics.", category: "Trading analytics", readingTime: "11 min read", intro: "Trading journal metrics are most useful when they answer a specific review question and are read with sample size, costs and context.", sections: [
    { id: "metrics-one", heading: "Outcome and risk metrics", content: [table(["Metric", "Formula or definition", "Useful question"], [["Net P&L", "Gross P&L − charges", "What remained after costs?"], ["Win rate", "Winning trades ÷ total trades", "How often did trades close positive?"], ["Average winner", "Winning P&L ÷ winning trades", "What does a win contribute?"], ["Average loser", "Losing P&L ÷ losing trades", "What does a loss cost?"], ["Risk-reward ratio", "Planned reward ÷ planned risk", "What was planned?"], ["Profit factor", "Gross profit ÷ gross loss", "How do wins compare with losses?"], ["Expectancy", "(Win probability × average win) − (loss probability × average loss)", "What is the average result per trade?"]]) ] },
    { id: "metrics-two", heading: "Distribution and behaviour metrics", content: [table(["Metric", "Definition", "Limitation"], [["R-multiple", "Net P&L ÷ planned rupee risk", "Depends on consistent risk estimates"], ["Maximum drawdown", "Largest peak-to-trough decline", "Historical, not a guarantee"], ["Consecutive wins/losses", "Longest observed streak", "Sensitive to sample size"], ["Average holding time", "Mean time in completed trades", "Mean hides skew"], ["MFE", "Best unrealised excursion during trade", "Needs path or chart data"], ["MAE", "Worst unrealised excursion during trade", "Scaling complicates attribution"], ["Setup performance", "Results grouped by setup", "Tags must be consistent"], ["Time-of-day performance", "Results grouped by time window", "Time zones and sample sizes matter"]]) ] },
    { id: "limitations", heading: "How to interpret metrics safely", content: [p("No metric guarantees profitability. A high win rate can coexist with large losses, and a good profit factor can be driven by one outlier. Segment metrics only after you have enough comparable observations, keep costs consistent, and inspect the underlying trades rather than trusting a single dashboard number.")] },
  ], relatedSlugs: ["profit-factor-vs-win-rate", "trading-expectancy-explained", "mfe-mae-trading"], internalLinks: [links.analytics, links.product], cta: "Choose one metric for one review question, then inspect the trades behind it." }),

  article({ slug: "profit-factor-vs-win-rate", title: "Profit Factor vs Win Rate: Which Metric Matters More?", description: "Compare profit factor and win rate with formulas, worked examples and sample-size limitations.", category: "Trading analytics", readingTime: "8 min read", intro: "Profit factor and win rate describe different parts of a strategy. Neither is sufficient on its own to judge a trading process.", sections: [
    { id: "definitions", heading: "Definitions and formulas", content: [p("Win rate = winning trades ÷ total trades. Profit factor = gross profit from winning trades ÷ absolute gross loss from losing trades. A profit factor above 1 means gross profits exceeded gross losses in the selected sample, before any costs not included in the data."), p("Expectancy adds another useful lens: (win probability × average win) − (loss probability × average loss). Use the same trade population and cost treatment when comparing metrics.")] },
    { id: "examples", heading: "Two worked strategy examples", content: [table(["Strategy", "Wins / losses", "Win rate", "Average win / loss", "Interpretation"], [["A: frequent small wins", "18 / 2", "90%", "₹50 / ₹600", "Gross result = ₹300; high win rate but poor outcome"], ["B: fewer larger wins", "8 / 12", "40%", "₹300 / ₹80", "Gross result = ₹1,440; lower win rate but positive expectancy"]]), p("These are fictional, simplified examples. They exclude charges and do not predict future results. Strategy B has expectancy (0.40 × 300) − (0.60 × 80) = ₹72 per trade; Strategy A has (0.90 × 50) − (0.10 × 600) = −₹15 per trade.")] },
    { id: "limits", heading: "Why neither metric should stand alone", content: [p("Profit factor and win rate are sensitive to outliers, sample size, regime and execution costs. Pair them with average win, average loss, net P&L, drawdown, R-multiple and the actual tagged trades. Twenty trades can provide a clue; it is not a stable verdict about a strategy.")] },
  ], relatedSlugs: ["trading-journal-metrics", "trading-expectancy-explained"], internalLinks: [links.analytics, { label: "Read the trading metrics guide", href: "/blog/trading-journal-metrics" }], cta: "Read win rate and profit factor together, then open the trades that created them." }),

  article({ slug: "trading-expectancy-explained", title: "Trading Expectancy Explained With Formula and Examples", description: "Learn the trading expectancy formula, positive and negative expectancy, and how to segment results.", category: "Trading analytics", readingTime: "8 min read", intro: "Trading expectancy estimates the average result per trade from win probability, average win and average loss.", sections: [
    { id: "formula", heading: "The expectancy formula", content: [p("Expectancy = (win probability × average win) − (loss probability × average loss). If 40% of trades win, the win probability is 0.40 and the loss probability is 0.60. Use positive magnitudes for average win and average loss in the formula."), p("A positive expectancy means the selected sample's average result was positive before any omitted costs. A negative expectancy means the opposite. It is an estimate, not a promise.")] },
    { id: "examples", heading: "Two worked examples", content: [table(["Sample", "Calculation", "Expectancy"], [["Positive", "0.40 × ₹300 − 0.60 × ₹80", "₹72 per trade"], ["Negative", "0.65 × ₹100 − 0.35 × ₹250", "−₹22.50 per trade"]]), p("The examples are fictional. If charges average ₹20 per trade, the first sample's net expectancy would be about ₹52, assuming the charge treatment is comparable. Keep gross and net calculations clearly labelled.")] },
    { id: "segment", heading: "Segment expectancy, not just total expectancy", content: [p("Calculate expectancy by strategy, instrument and time of day when each group has enough observations. A positive total can hide a weak setup, and a weak total can include one useful process that deserves more testing."), list("Use consistent setup tags.", "Compare equal periods and the same cost treatment.", "Report the number of trades with every segment.", "Inspect outliers and the largest drawdown alongside the average.")] },
    { id: "limits", heading: "Sample-size limitations", content: [p("Expectancy moves when one large winner or loser enters a small sample. Treat early results as evidence to investigate, not as a forecast. Continue recording the underlying trades and revisit the estimate after a broader, comparable sample.")] },
  ], relatedSlugs: ["profit-factor-vs-win-rate", "trading-journal-metrics"], internalLinks: [links.analytics, { label: "Profit factor vs win rate", href: "/blog/profit-factor-vs-win-rate" }], cta: "Use expectancy to frame a review question, not to promise an outcome." }),

  article({ slug: "mfe-mae-trading", title: "MFE and MAE in Trading: Improve Stops and Exits", description: "Understand Maximum Favourable Excursion and Maximum Adverse Excursion with placeholder chart data and practical limits.", category: "Advanced analytics", readingTime: "8 min read", intro: "MFE and MAE describe the best and worst unrealised movement a trade experienced before it closed.", sections: [
    { id: "definitions", heading: "What MFE and MAE mean", content: [p("Maximum Favourable Excursion (MFE) is the most favourable unrealised movement during a trade. Maximum Adverse Excursion (MAE) is the most unfavourable unrealised movement. The exact calculation depends on direction, price path, and whether the data is tick, candle or mark based."), p("[SCREENSHOT REQUIRED: TradeLore trade chart showing MFE and MAE]") ] },
    { id: "chart", heading: "Placeholder chart example", content: [table(["Trade", "Entry", "MAE", "MFE", "Exit", "Observation"], [["T1", "100", "−8", "+25", "118", "Exit left some favourable movement"], ["T2", "100", "−12", "+6", "94", "Adverse move preceded stop"], ["T3", "100", "−3", "+18", "103", "Possible early exit"]]), p("Plot entry at zero, MAE below zero and MFE above zero. The table is placeholder data, not a TradeLore screenshot or historical result.")] },
    { id: "use", heading: "Questions MFE and MAE can support", content: [list("Stop-loss placement: did stopped trades exceed a common adverse range?", "Premature exits: did many exits occur before a larger favourable move?", "Target placement: where did favourable movement commonly stall?", "Trade management: did partial exits change the distribution?")] },
    { id: "limits", heading: "Scaling in and out makes attribution harder", content: [p("When quantity changes, define whether MFE and MAE are measured per leg, per position or per combined trade. Candle highs and lows can overstate the executable path. Use the same convention across the sample and keep the raw executions available for inspection.")] },
  ], relatedSlugs: ["trading-journal-metrics", "r-multiple-risk-reward-ratio"], internalLinks: [links.replay, links.analytics], cta: "Use MFE and MAE to ask better stop and exit questions, not to retrofit certainty." }),

  article({ slug: "r-multiple-risk-reward-ratio", title: "R-Multiple vs Risk-Reward Ratio: A Practical Guide", description: "Understand planned risk-reward and realised R-multiple with full-stop, target, partial-exit and early-exit examples.", category: "Risk metrics", readingTime: "8 min read", intro: "Risk-reward describes the plan; R-multiple describes the realised result relative to the rupee risk you accepted.", sections: [
    { id: "terms", heading: "Planned versus realised", content: [p("Planned risk is the rupee loss at the defined stop, including the position size you intended to take. Planned risk-reward is planned reward divided by planned risk. Realised R-multiple is realised net P&L divided by planned risk."), p("A ₹500 result and a ₹500 loss do not mean the same thing if the trades carried different planned risks. R-multiple provides a common unit for review, provided risk was recorded consistently.")] },
    { id: "examples", heading: "Four examples", content: [table(["Outcome", "Planned risk", "Net result", "R-multiple"], [["Full stop-loss", "₹500", "−₹500", "−1R"], ["Full target", "₹500", "+₹1,000", "+2R"], ["Partial exit", "₹500", "+₹500", "+1R"], ["Early exit", "₹500", "+₹150", "+0.3R"]]), p("These examples exclude any unrecorded charges. If you use gross result for R-multiple, label it gross; net R is more useful for cost-aware review.")] },
    { id: "limits", heading: "Limitations", content: [p("R-multiple is only as good as the planned-risk field. Moving a stop after entry, adding to a position, or combining several legs can change the denominator. Record the original plan and later changes instead of rewriting history.")] },
  ], relatedSlugs: ["trading-journal-metrics", "mfe-mae-trading"], internalLinks: [links.analytics, { label: "Trading journal metrics", href: "/blog/trading-journal-metrics" }], cta: "Record planned risk before entry so the review unit cannot move after the outcome." }),

  article({ slug: "weekly-trading-review-process", title: "A 30-Minute Weekly Trading Review Process", description: "A printable 30-minute weekly trading review checklist with questions, an example summary and a TradeLore workflow.", category: "Trading review", readingTime: "7 min read", intro: "A weekly review should end with one specific improvement, not a longer list of vague intentions.", sections: [
    { id: "checklist", heading: "The 30-minute checklist", content: [table(["Time", "Review"], [["0–3 min", "Net P&L and number of trades"], ["3–7 min", "Strategy performance"], ["7–10 min", "Best and worst trade"], ["10–14 min", "Mistakes and rule adherence"], ["14–18 min", "Time of day and position sizing"], ["18–23 min", "Costliest behaviour"], ["23–27 min", "Replay one representative trade"], ["27–30 min", "Choose one improvement"]]), list("[ ] Net P&L reviewed after charges", "[ ] Strategies tagged consistently", "[ ] Best and worst trades opened", "[ ] Mistakes and rule adherence recorded", "[ ] Time, sizing and costliest behaviour checked", "[ ] One next-week rule written")] },
    { id: "questions", heading: "Questions to ask", content: [list("Was the result driven by execution, setup, size or cost?", "Which rule was followed most reliably?", "Which behaviour had the largest avoidable effect?", "What would I repeat even if the result was negative?", "What one observable action changes next week?")] },
    { id: "example", heading: "Example weekly summary", content: [p("Fictional summary: net P&L was ₹420 across 12 trades. The morning setup tag had the clearest sample, while late entries were the most common mistake. Rule adherence was strong in size but weak in stop placement. Next week's single improvement is to enter the planned stop before sending the order and review it after exit."), p("In TradeLore, a simple workflow is: sync or import trades, complete journal fields, review reports, replay one trade, and capture the next rule in your journal or playbook. This is a process suggestion, not a profitability promise.")] },
  ], relatedSlugs: ["how-to-track-trading-mistakes", "best-time-to-trade-journal-analysis"], internalLinks: [links.notes, links.analytics, links.replay], cta: "Finish the review with one action you can observe next week." }),

  article({ slug: "best-time-to-trade-journal-analysis", title: "How to Find Your Best Trading Time Using Journal Data", description: "Analyse personal performance by time, weekday, expiry, instrument and strategy without assuming a universal best trading time.", category: "Performance analysis", readingTime: "8 min read", intro: "There is no universal best time to trade. Your journal can show when your own process has been more consistent, subject to enough comparable data.", sections: [
    { id: "segments", heading: "Useful time segments", content: [list("First 15 minutes", "Morning session", "Midday", "Final hour", "Day of week", "Expiry day versus non-expiry day", "Instrument and strategy", "Long versus short") ] },
    { id: "dataset", heading: "Example dataset", content: [table(["Window", "Trades", "Net P&L", "Win rate", "Question"], [["First 15 min", "8", "−₹240", "38%", "Was execution rushed?"], ["Morning", "20", "+₹600", "55%", "Is the sample repeatable?"], ["Midday", "5", "+₹40", "60%", "Too few observations?"], ["Final hour", "12", "−₹180", "42%", "Did fatigue or size matter?"]]), p("This is fictional data. Do not call a window your best or worst from five trades. Include trade count, net costs, setup mix and drawdown with every comparison.")] },
    { id: "method", heading: "A simple analysis method", content: [p("Add a consistent time-window tag, then compare net P&L, expectancy, average loss, rule adherence and sample size. Repeat the cut by strategy and instrument before changing a schedule. The aim is to find a testable process boundary, not a market-wide rule."), p("Time zones, daylight-saving assumptions in external data, expiry mix and changing volatility can distort comparisons. Keep the date range visible.")] },
  ], relatedSlugs: ["trading-journal-metrics", "weekly-trading-review-process"], internalLinks: [links.analytics, { label: "Trading journal metrics", href: "/blog/trading-journal-metrics" }], cta: "Let your own tagged sample challenge assumptions about timing." }),

  article({ slug: "how-to-track-trading-mistakes", title: "How to Track Trading Mistakes and Stop Repeating Them", description: "Create consistent mistake tags, measure their impact and choose one behavioural improvement at a time.", category: "Trading behaviour", readingTime: "7 min read", intro: "A mistake log works when tags describe observable actions and connect them to the trade result.", sections: [
    { id: "tags", heading: "Useful mistake tags", content: [list("FOMO", "Revenge trading", "Overtrading", "Oversizing", "Late entry", "Early exit", "Moving stop-loss", "No confirmation", "Outside the plan", "Low-quality setup", "Ignoring maximum daily loss")] },
    { id: "method", heading: "How to record consistently", content: [p("Define each tag in one sentence. For example, ‘late entry’ means entering after the planned trigger, not merely entering later in the session. Apply tags after the trade using the same definitions, and allow more than one tag only when both actions are visible."), list("Record the planned rule before entry.", "Tag the observable deviation after exit.", "Store a short note with evidence, not a judgement.", "Keep the tag list stable long enough to compare.")] },
    { id: "impact", heading: "Measure financial impact", content: [p("Group net P&L, average loss, frequency and R-multiple by mistake tag. A tag with the largest total loss may simply occur more often; also inspect per-trade impact and the trades without that tag. Use this evidence to choose one behaviour to test next."), p("Do not treat a loss as proof of a mistake. A rule-following loss can be part of the process; a rule-breaking win is still worth recording.")] },
    { id: "improvement", heading: "Choose one improvement", content: [p("Pick the highest-confidence recurring behaviour, define a visible check, and review it next week. Examples include a pre-entry confirmation checkbox, a fixed size rule, or a maximum daily-loss stop. This is workflow education, not mental-health or medical advice.")] },
  ], relatedSlugs: ["trading-psychology-journal", "weekly-trading-review-process"], internalLinks: [links.notes, links.analytics], cta: "Name the action, measure its occurrence, and change one behaviour at a time." }),

  article({ slug: "trading-psychology-journal", title: "Trading Psychology Journal: How to Track Emotions", description: "A practical, non-clinical framework for recording emotions and comparing them with trading behaviour and results.", category: "Trading behaviour", readingTime: "7 min read", intro: "A trading psychology journal is a record of state and behaviour, not a diagnosis. Its purpose is to reveal whether emotional tags coincide with different decisions.", sections: [
    { id: "fields", heading: "What to record", content: [list("Emotional state before entry", "Confidence and stress", "Fear, FOMO and frustration", "Response after a loss", "Response after a winning streak", "Rule adherence", "Impulsive position-size changes") ] },
    { id: "compare", heading: "Compare emotion with trading data", content: [p("Use consistent tags, then compare them with expectancy, average loss, trade frequency, strategy, holding time and net P&L. Keep the comparison descriptive: ‘FOMO-tagged trades had shorter holding time in this sample’ is more useful than a broad label about character."), table(["Tag", "Compare", "Review question"], [["Stress", "Average loss and size", "Did size change when stress was high?"], ["FOMO", "Entry time and strategy", "Were entries outside the plan?"], ["Frustration", "Trade frequency", "Did one loss lead to extra trades?"], ["Winning streak", "Rule adherence", "Did confidence change sizing?"]]) ] },
    { id: "limits", heading: "Keep the journal non-clinical", content: [p("Do not use a trading journal to diagnose psychological conditions or replace professional support. Record what you noticed, what you did, and what rule you will test. If the process feels unsafe or overwhelming, pause trading and seek appropriate support outside the journal.")] },
  ], relatedSlugs: ["how-to-track-trading-mistakes", "trading-journal-metrics"], internalLinks: [links.notes, { label: "Track trading mistakes", href: "/blog/how-to-track-trading-mistakes" }], cta: "Describe the state and the action separately; that makes the review more useful." }),

  article({ slug: "how-to-review-options-trade-example", title: "How to Review an Options Trade: Complete Example", description: "A fictional NIFTY options trade review covering thesis, execution, risk, charges, MFE, MAE and lessons.", category: "Options journaling", readingTime: "9 min read", intro: "This is a fictional educational example and not a trade recommendation. It shows how one options trade can be reviewed from context through lesson.", sections: [
    { id: "setup", heading: "Market context and thesis", content: [p("Fictional context: the trader observed a defined intraday range and wrote a conditional bullish thesis before entry. The thesis was invalid if price failed the planned level; it was not a prediction or recommendation."), table(["Field", "Fictional entry"], [["Instrument", "NIFTY 25,000 CE"], ["Expiry", "26 Jun 2026"], ["Entry", "₹120"], ["Stop-loss / target", "₹95 / ₹170"], ["Quantity", "75"], ["Planned risk", "₹1,875"]]) ] },
    { id: "execution", heading: "Execution and outcome", content: [p("The trader entered one lot at ₹120, moved to ₹155, exited 50 units at ₹150 and the remaining 25 at ₹138. Gross P&L was (₹150 − ₹120) × 50 + (₹138 − ₹120) × 25 = ₹1,950. Charges are intentionally a placeholder: net P&L = ₹1,950 − [CHARGES PLACEHOLDER]."), p("MFE was recorded as +₹42 per option from the entry price and MAE as −₹10 per option. These are fictional values and depend on the chosen price-path convention."), p("[SCREENSHOT REQUIRED: TradeLore trade-review page using anonymised or demo data]") ] },
    { id: "review", heading: "Review the decision", content: [table(["Review item", "Observation"], [["Rule adherence", "Entry followed the written condition"], ["Partial exit", "Reduced exposure before the final exit"], ["Mistake", "Target was not redefined after partial exit"], ["Emotion", "Confidence rose after the first move"], ["Lesson", "Write the management rule before entry"], ["Repeat", "Pre-trade invalidation and size"], ["Change", "Define partial-exit handling in advance"]]), p("The rupee result alone does not decide whether the trade was good. Review thesis, risk, execution, costs and behaviour separately. Do not generalise one fictional example into a strategy claim.")] },
  ], relatedSlugs: ["how-to-maintain-fno-trading-journal", "mfe-mae-trading"], internalLinks: [links.replay, links.notes, { label: "Options trading journal India", href: "/options-trading-journal-india" }], cta: "Use the example structure to review one real trade without rewriting the original plan." }),
] as const satisfies readonly BlogPost[];

export const publishedBlogPosts = blogPosts.filter((post) => post.published);
export function getPublishedBlogPost(slug: string) { return publishedBlogPosts.find((post) => post.slug === slug); }
export function blogUrl(slug?: string) { return `${siteUrl}/blog${slug ? `/${slug}` : ""}`; }
